version: '3.9'

services:
  my-awesome-app-aer:
    container_name: my-awesome-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - '/app/node_modules'
    ports:
      - '3001:3000'

  my-awesome-app-test:
    container_name: awesome-app_test
    image: my-awesome-app-aer_my-awesome-app-dev
    volumes:
      - .:/app
      - '/app/node_modules'
    command: ["npm", "run", "test"]