name: Docker Dev Image CI

env: 
  DATE_STAMP: $(date +%s)

on:
  pull_request: 
    branches: [main]
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Build the Docker image
       run: docker build . -f "Dockerfile" -t "andyrod209/my-awesome-app-aer:latest"
     
     - name: Env variables
       run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV
       
     - name: Add "date-stamp" tag to the image
       run: docker image tag andyrod209/my-awesome-app-aer:latest andyrod209/my-awesome-app-aer:${{env.date-stamp}}
       
     - name: login to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
     - name: Push the Docker image to Docker Hub
        run: docker push --all-tags andyrod209/my-awesome-app-aer