name: Docker Dev Image CI

env: 
  DATE_STAMP: $(date +%s)

on:
  workflow_dispatch:

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Env variables
        run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV

      - name: Build a docker image
        run: docker build . --file Dockerfile --tag andyrod209/my-awesome-app-aer:${{ env.date-stamp }}